

<div id="page-wrapper">

    <div class="row">
        <div class="col-lg-12">
            <h1>Visor Page <small>PeruQuiosco</small></h1>
            <ol class="breadcrumb">
                <li><a href="index.html"><i class="icon-dashboard"></i> Dashboard</a></li>
                <li class="active"><i class="icon-file-alt"></i> Visor Page</li>
            </ol>

















<!--            <div class="col-lg-6">
                <h1>form 1</h1>
                <form role="form">
                    <div class="form-group">
                        <label for="ejemplo_email_1">Email</label>
                        <input type="email" class="form-control" id="ejemplo_email_1"
                               placeholder="Introduce tu email">
                    </div>
                    <div class="form-group">
                        <label for="ejemplo_password_1">Contraseña</label>
                        <input type="password" class="form-control" id="ejemplo_password_1" 
                               placeholder="Contraseña">
                    </div>
                    <div class="form-group">
                        <label for="ejemplo_archivo_1">Adjuntar un archivo</label>
                        <input type="file" id="ejemplo_archivo_1">
                        <p class="help-block">Ejemplo de texto de ayuda.</p>
                    </div>
                    <div class="checkbox">
                        <label>
                            <input type="checkbox"> Activa esta casilla
                        </label>
                    </div>
                    <button type="submit" class="btn btn-default">Enviar</button>
                </form>

                 Form 

                <h1>form 2</h1>
                <form class="form-inline" role="form">
                    <div class="form-group">
                        <label class="sr-only" for="ejemplo_email_2">Email</label>
                        <input type="email" class="form-control" id="ejemplo_email_2"
                               placeholder="Introduce tu email">
                    </div>
                    <div class="form-group">
                        <label class="sr-only" for="ejemplo_password_2">Contraseña</label>
                        <input type="password" class="form-control" id="ejemplo_password_2" 
                               placeholder="Contraseña">
                    </div>
                    <div class="checkbox">
                        <label>
                            <input type="checkbox"> No cerrar sesión
                        </label>
                    </div>
                    <button type="submit" class="btn btn-default">Entrar</button>
                </form>
                 Form 

            </div>-->

            <div class="col-lg-8">
                <h1>Registrese</h1>
                <form class="form-horizontal" role="form">
                    <div class="form-group">
                        <label for="ejemplo_email_3" class="col-lg-2 control-label">Email</label>
                        <div class="col-lg-8">
                            <input type="email" class="form-control input-sm" id="ejemplo_email_3"
                                   placeholder="Email">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="ejemplo_password_3" class="col-lg-2 control-label">Contraseña</label>
                        <div class="col-lg-8">
                            <input type="password" class="form-control input-sm" id="ejemplo_password_3" 
                                   placeholder="Contraseña">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-lg-offset-2 col-lg-8">
                            <button type="submit" class="btn btn-default">Entrar</button>
                        </div>
                    </div>
                </form>
                <!-- Form -->

            </div>

































        </div>
    </div><!-- /.row -->

</div><!-- /#page-wrapper -->

