<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1>Post <small>Lista de post </small></h1>
            <ol class="breadcrumb">
                <li><a href="/"><i class="fa fa-dashboard"></i> Dashboard</a></li>
                <li class="active"><i class="fa fa-edit"></i> Posts</li>
            </ol>
            <div class="alert alert-info alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                Visit <a class="alert-link" target="_blank" href="http://getbootstrap.com/css/#forms">Bootstrap's Form Documentation</a> for more information.
            </div>
        </div>
    </div><!-- /.row -->
    <div class="row">
        <div class="col-lg-1"></div>
        <div class="col-lg-10">
            <form class="form-horizontal " role="form">
                <div class="form-group">
                    <label for="ejemplo_email_3" class="col-lg-2 control-label ">Email</label>
                    <div class="col-lg-10">
                        <input type="email" class="form-control" id="ejemplo_email_3"
                               placeholder="Email">
                    </div>
                </div>
                <div class="form-group">
                    <label for="ejemplo_password_3" class="col-lg-2 control-label">Contraseña</label>
                    <div class="col-lg-10">
                        <input type="password" class="form-control" id="ejemplo_password_3" 
                               placeholder="Contraseña">
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-lg-offset-2 col-lg-10">
                        <div class="checkbox">
                            <label>
                                <input type="checkbox"> No cerrar sesión
                            </label>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-lg-offset-2 col-lg-10">
                        <button type="submit" class="btn btn-default">Entrar</button>
                    </div>
                </div>
            </form>
            <a href="/posts/listar">Listar</a>
            <?php echo $this->form; ?>
        </div>
        <div class="col-lg-1"></div>
    </div>
</div>