<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1>Post <small>Lista de post </small></h1>
            <ol class="breadcrumb">
                <li><a href="/"><i class="fa fa-dashboard"></i> Dashboard</a></li>
                <li class="active"><i class="fa fa-edit"></i> Posts</li>
            </ol>
            <div class="alert alert-info alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                Visit <a class="alert-link" target="_blank" href="http://getbootstrap.com/css/#forms">Bootstrap's Form Documentation</a> for more information.
            </div>
        </div>
    </div><!-- /.row -->
    <div class="row">
        <div class="col-lg-12">
<!--            <h3><a href="/posts/agregar">Agregar</a></h3>-->
            <a href="/posts/listar"><button class="btn btn-primary" type="button">
                Listar</button></a>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-1">
        </div>
        <div class="col-lg-9">
            <?php echo $this->form; ?>
        </div>
        <div class="col-lg-2"></div>
    </div>
</div>