
<div id="page-wrapper">
     <div class="row">
        <div class="col-lg-12">
            <h1>Post <small>Lista de post </small></h1>
            <ol class="breadcrumb">
                <li><a href="/"><i class="fa fa-dashboard"></i> Dashboard</a></li>
                <li class="active"><i class="fa fa-edit"></i> Posts</li>
            </ol>
            <div class="alert alert-info alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                Visit <a class="alert-link" target="_blank" href="http://getbootstrap.com/css/#forms">Bootstrap's Form Documentation</a> for more information.
            </div>
        </div>
    </div><!-- /.row -->
    <div class="row">
        <div class="col-lg-12">
<!--            <h3><a href="/posts/agregar">Agregar</a></h3>-->
            <a href="/posts/agregar"><button class="btn btn-primary" type="button">Agregar</button></a>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-2">
        </div>
        <div class="col-lg-8">
            <div class="table-responsive">
                <table class="table  table-bordered table-hover tablesorter">
                    <thead>
                        <tr>
                            <th class="header">Id <i class="fa fa-sort"></i></th>
                            <th class="header">Titulo <i class="fa fa-sort"></i></th>
                            <th class="header">Fecha <i class="fa fa-sort"></i></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php if (count($this->posts)): ?>
                            <?php foreach ($this->posts as $post) : ?>
                                <tr>
                                    <td><?php echo $post->id; ?></td>
                                    <td><?php echo $post->title; ?></td>
                                    <td><?php echo $post->created_at; ?></td>
                                </tr>        
                            <?php endforeach; ?>
                        <?php else: ?>
                            <tr>
                                <td colspan='3'>No hay datos</td>
                            </tr>
                        <?php endif; ?>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="col-lg-2">
        </div>
    </div>
</div><!-- /#page-wrapper -->

