<div id="page-wrapper">
    <a href="/posts/agregar">Agregar</a>
    <table class="table">
        <tr>
            <td>Id</td>
            <td>Titulo</td>
            <td>Fecha</td>
        </tr>
        <?php if(count($this->posts)):?>
            <?php foreach ($this->posts as $post) :?>
        <tr>
            <td><?php echo $post->id;?></td>
            <td><?php echo $post->title;?></td>
            <td><?php echo $post->created_at;?></td>
        </tr>        
            <?php endforeach;?>
        <?php else:?>
        <tr>
            <td colspan='3'>No hay datos</td>
        </tr>
        <?php endif;?>
    </table>
</div><!-- /#page-wrapper -->
